# default config
baseurl = "https://lafisrap.github.io/"
languageCode = "de-DE"
title = "Der Garten des Epikur | Spielplatz fÃ¼r Kinder und Erwachsene"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"

# google analytics
googleAnalytics = "" # example : UA-123-45

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

[languages]
  [languages.de]
    contentDir = "content/de"
    title = 'Der Garten des Epikur | Spielplatz fÃ¼r Kinder und Erwachsene'
    languageName = "Deutsch"
    languageNameShort = "de"
    languageFlag = "ğŸ‡©ğŸ‡ª"
    addressLabel = "Adresse"
    contactLabel = "Kontaktinfo"
    postBy = "Beitrag von"
    searchLabel = "Suche"

    weight = 1
    [languages.de.params]
      home = "ğŸ "
      readmore = "weiter"
    [[languages.de.menu.main]]
      name = 'ğŸ '
      url = 'de'
    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "Das Spielzimmer"
      url = "de/homepage/playroom/"
      weight = 1

    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "Iris"
      url = "de/homepage/iris/"
      weight = 1

    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "Filip"
      url = "de/homepage/filip/"
      weight = 2

    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "Esamael"
      url = "de/homepage/esamael/"
      weight = 3

  [languages.en]
    contentDir = "content/en"
    title = 'The Garden of Epicurus | Playground for children and adults'
    languageName = "English"
    languageNameShort = "en"
    languageFlag = "ğŸ‡¬ğŸ‡§"
    weight = 2
    [[languages.en.menu.main]]
      name = 'Home'
  [languages.se]
    contentDir = "content/se"
    title = 'Epikurus trÃ¤dgÃ¥rd | Lekplats fÃ¶r barn och vuxna'
    languageName = "Svenska"
    languageNameShort = "se"
    languageFlag = "ğŸ‡¸ğŸ‡ª"
    addressLabel = "Adress"
    contactLabel = "Kontaktuppgifter"
    postBy = "Post av"
    searchLabel = "SÃ¶k pÃ¥"
    weight = 3
    
    [languages.se.params]
      home = "ğŸ "
      readmore = "lÃ¤s mer"
    [[languages.se.menu.main]]
      name = 'ğŸ '
      url = 'se'
    [[languages.se.menu.main]]
      parent = "ğŸ "
      name = "Das Spielzimmer"
      url = "se/homepage/playroom/"
      weight = 1

    [[languages.se.menu.main]]
      parent = "ğŸ "
      name = "Iris"
      url = "se/homepage/iris/"
      weight = 1

    [[languages.se.menu.main]]
      parent = "ğŸ "
      name = "Filip"
      url = "se/homepage/filip/"
      weight = 2

    [[languages.se.menu.main]]
      parent = "ğŸ "
      name = "Esamael"
      url = "se/homepage/esamael/"
      weight = 3

# navigation
[[menu.main]]
name = "Home"
url = ""
weight = 1
hasChildren = true

[[menu.main]]
parent = "Home"
name = "Das Spielzimmer"
url = "homepage/playroom/"

[[menu.main]]
parent = "Home"
name = "Iris"
url = "homepage/iris/"

[[menu.main]]
parent = "Home"
name = "Filip"
url = "homepage/filip/"

[[menu.main]]
parent = "Home"
name = "Esamael"
url = "homepage/esamael/"

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Contact"
url = "contact/"
weight = 3

# devault parameter
[params]
logo = "images/logo.png"
home = "Home"
layout = "1"
description = "This is meta description"
preloader = true
search = true
author = "Michael Schmidt"
author_image = "images/banner-img.png"
bio = "..."
mobile = "+49 163 ... ... ..."
email = "michael@epikur.berlin"
addressLabel = "Address"
address = "Turiner StraÃŸe 21, 13347 Berlin"
contactLabel = "Contact Info"
contact_form_action = "#"
copyright = "Copyright &copy; 2023 a theme by [themefisher.com](https://themefisher.com)"
readmore = "read more"
postBy = "Post by"
searchLabel = "Search"



# Instagram feed
[params.instafeed]
enable = true
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
link = "https://facebook.com/themefisher"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"

[[params.social]]
icon = "ti-linkedin"
link = "#"

[[params.social]]
icon = "ti-github"
link = "#"
