# default config
baseurl = "https://cypherpunk-academy.github.io/michaelschmidt.berlin"
languageCode = "de-DE"
title = "Allgemeine Gedankenfehler - Herausforderungen auf dem Weg zur Freiheit"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = "true"

# google analytics
googleAnalytics = "" # example : UA-123-45

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

[languages]
  [languages.de]
    contentDir = "content/de"
    title = 'Allgemeine Gedankenfehler des westlichen Kultur'
    languageName = "Deutsch"
    languageNameShort = "de"
    languageFlag = "ğŸ‡©ğŸ‡ª"
    addressLabel = "Adresse"
    contactLabel = "Kontakt"
    postBy = "Beitrag von"
    searchLabel = "Suche"
    latestPosts = "NEUE POSTS"

    weight = 1
    [languages.de.params]
      home = "ğŸ "
      readmore = "weiter"

    [[languages.de.menu.main]]
      name = 'ğŸ '
      url = 'de'

    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "Gedankenfehler"
      url = "de/homepage/gedankenfehler/"
      weight = 1

    [[languages.de.menu.main]]
      parent = "Gedankenfehler"
      name = "Erziehung"
      url = "de/homepage/gedankenfehler/erziehung"
      weight = 1

    [[languages.de.menu.main]]
      parent = "Gedankenfehler"
      name = "Fehler machen"
      url = "de/homepage/gedankenfehler/fehler"
      weight = 2

    [[languages.de.menu.main]]
      parent = "Gedankenfehler"
      name = "Zufriedenheit"
      url = "de/homepage/gedankenfehler/zufriedenheit"
      weight = 3

    [[languages.de.menu.main]]
      parent = "Gedankenfehler"
      name = "Angst"
      url = "de/homepage/gedankenfehler/angst"
      weight = 4

    [[languages.de.menu.main]]
      parent = "Gedankenfehler"
      name = "Worte"
      url = "de/homepage/gedankenfehler/worte"
      weight = 5

    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "Die Philosophie der Freiheit"
      url = "de/homepage/dpdf/"
      weight = 2

    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "2064 - Cypherpunks"
      url = "de/homepage/2064/"
      weight = 3

    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "Sophia"
      url = "de/homepage/sophia/"
      weight = 4

    [[languages.de.menu.main]]
      parent = "ğŸ "
      name = "Verschiedenes"
      url = "de/homepage/verschiedenes/"
      weight = 5

# navigation
[[menu.main]]
name = "Home"
url = ""
weight = 1
hasChildren = true

[[menu.main]]
parent = "Home"
name = "Das Spielzimmer"
url = "homepage/playroom/"

[[menu.main]]
parent = "Home"
name = "Iris"
url = "homepage/iris/"

[[menu.main]]
parent = "Home"
name = "Filip"
url = "homepage/filip/"

[[menu.main]]
parent = "Home"
name = "Esamael"
url = "homepage/esamael/"

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Contact"
url = "contact/"
weight = 3

# devault parameter
[params]
logo = "images/logo1.png"
home = "Home"
layout = "1"
description = "This is meta description"
preloader = true
search = true
author = "Michael Schmidt"
author_image = "images/banner-img.png"
bio = "..."
mobile = "+49 163 ... ... ..."
email = "michael@epikur.berlin"
addressLabel = "Address"
address = "Turiner StraÃŸe 21, 13347 Berlin"
contactLabel = "Contact Info"
contact_form_action = "#"
copyright = "Copyright &copy; 2023 a theme by [themefisher.com](https://themefisher.com)"
readmore = "read more"
postBy = "Post by"
searchLabel = "Search"



# Instagram feed
[params.instafeed]
enable = true
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
link = "https://facebook.com/themefisher"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"

[[params.social]]
icon = "ti-linkedin"
link = "#"

[[params.social]]
icon = "ti-github"
link = "#"
